[variables]
NODE_ENV = "development"
PORT = "3000"

[phases.setup]
providers = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"